name: Tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  go_test:
    name: Main Tests
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13, ubuntu-24.04-arm]
        go: ["1.24"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Run Main Tests
        run: |
          go test -v

  test_examples:
    name: Test Examples
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: [ "1.24" ]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Test Examples
        run: make test.examples
  test-arrow:
    name: Test Arrow
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go: [ "1.24" ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Run Arrow Tests
        run: go test -v -tags=duckdb_arrow
  test-dynamic-lib:
    name: Dynamic Lib Tests
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - os: "macos-13"
            filename: "libduckdb-osx-universal"
            ld_path_env_name: "DYLD_LIBRARY_PATH"
          - os: "macos-14"
            filename: "libduckdb-osx-universal"
            ld_path_env_name: "DYLD_LIBRARY_PATH"
          - os: "ubuntu-latest"
            filename: "libduckdb-linux-amd64"
            ld_path_env_name: "LD_LIBRARY_PATH"
          - os: "ubuntu-24.04-arm"
            filename: "libduckdb-linux-aarch64"
            ld_path_env_name: "LD_LIBRARY_PATH"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Run Dynamic Lib Tests
        run: |
          make test.dynamic.lib FILENAME=${{ matrix.filename }} VERSION=v1.2.0
          CGO_ENABLED=1 CGO_LDFLAGS="-lduckdb -L${SRCDIR}dynamic-dir" ${{ matrix.ld_path_env_name }}=${SRCDIR}dynamic-dir go test -tags=duckdb_use_lib
  test-static-lib-darwin-arm64:
    name: Static Lib Tests Darwin ARM64
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Run Static Lib Tests Darwin ARM64
        run: |
          make test.static.lib.darwin.arm64 VERSION=v1.2.0
          CGO_ENABLED=1 CPPFLAGS="-DDUCKDB_STATIC_BUILD" CGO_LDFLAGS="-lduckdb -lc++ -L${SRCDIR}static-dir" go test -tags=duckdb_use_static_lib
